# Azure build pipelines for Procdump-for-Linux

trigger:
    branches:
      include:
        - release/*
        - main
      exclude:
        - dev/*
        - test/*
  
pr:
- main

stages:
 - stage: "Build"
   jobs:
    - job: "Build_Procmon_Ubuntu_18_04_Package"
      pool: "Procmon-Ubuntu-18.04-Pool"
      condition: not(eq(variables['Build.Reason'], 'PullRequest'))
      steps:
      - script: |
          export REVISION=$(Build.BuildId)
          sed -i "s/999999/$REVISION/g" $(Build.SourcesDirectory)/CMakeLists.txt
          mkdir $(Build.SourcesDirectory)/build && cd $(Build.SourcesDirectory)/build
          cmake ..
          make
        displayName: "Build Ubuntu Procmon 18.04 Binary"
      
      - script: |
          mkdir $(Build.SourcesDirectory)/pkgbuild
          cd $(Build.SourcesDirectory)/build
          cpack ..
          mv *.deb $(Build.SourcesDirectory)/pkgbuild
        displayName: "Build Ubuntu Procmon 18.04 Package"
      
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)/pkgbuild/'
          TargetFolder: '$(Build.ArtifactStagingDirectory)/18.04/'
        displayName: 'Copy build to staging'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
        displayName: 'Copy to artifacts'
      
    - job: "Build_Procmon_Ubuntu_20_04_Package"
      pool: "Procmon-Ubuntu-20.04-Pool"
      condition: not(eq(variables['Build.Reason'], 'PullRequest'))
      steps:
         - script: |
             export REVISION=$(Build.BuildId)
             sed -i "s/999999/$REVISION/g" $(Build.SourcesDirectory)/CMakeLists.txt
             mkdir $(Build.SourcesDirectory)/build && cd $(Build.SourcesDirectory)/build
             cmake ..
             make
           displayName: "Build Procmon Ubuntu 20.04 Binary"
    
         - script: |
            mkdir $(Build.SourcesDirectory)/pkgbuild
            cd $(Build.SourcesDirectory)/build
            cpack ..
            mv *.deb $(Build.SourcesDirectory)/pkgbuild
           displayName: "Build Procmon Ubuntu 20.04 Package"
    
         - task: CopyFiles@2
           inputs:
             SourceFolder: '$(Build.SourcesDirectory)/pkgbuild/'
             TargetFolder: '$(Build.ArtifactStagingDirectory)/20.04/'
           displayName: 'Copy build to staging'

         - task: PublishBuildArtifacts@1
           inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
           displayName: 'Copy to artifacts'

 - stage: Sign
   jobs:
    - job: "Sign_Ubuntu_18_04"
      pool: "Procmon-Ubuntu-18.04-Pool"
      steps:
      - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
        displayName: 'ESRP CodeSigning DEB'
        inputs:
          ConnectedServiceName: 'Sysinternals ESRP CodeSigning'
          FolderPath: '$(Build.ArtifactStagingDirectory)/18.04'
          Pattern: '*.deb'
          signConfigType: inlineSignParams
          inlineOperation: |
            [
              {
                "keyCode": "CP-450779-Pgp",
                "OperationCode": "LinuxSign",
                "Parameters": {},
                "ToolName": "sign",
                "ToolVersion": "1.0"
              }
            ]

    - job: "Sign_Ubuntu_20_04"
      pool: "Procmon-Ubuntu-20.04-Pool"
      steps:
      - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
        displayName: 'ESRP CodeSigning DEB'
        inputs:
          ConnectedServiceName: 'Sysinternals ESRP CodeSigning'
          FolderPath: '$(Build.ArtifactStagingDirectory)/20.04'
          Pattern: '*.deb'
          signConfigType: inlineSignParams
          inlineOperation: |
            [
              {
                "keyCode": "CP-450779-Pgp",
                "OperationCode": "LinuxSign",
                "Parameters": {},
                "ToolName": "sign",
                "ToolVersion": "1.0"
              }
            ]

 